build:
  tests:
    before:
      - pecl install inotify
    override:
      - command:      './bin/phing unit'
        idle_timeout: 500
        coverage:
          file:   'test/coverage.xml'
          format: 'php-clover'
