build:
  project_setup:
    after:
      - pecl install inotify

  tests:
    override:
      - command:      './bin/phing unit'
        idle_timeout: 500
        coverage:
          file:   'test/coverage.xml'
          format: 'php-clover'
