language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - nightly

before_install:
  - sudo apt-get install tidy
  
install:
  - composer self-update
  - composer install
    
script: 
  - ./bin/phing unit
  
