<?php
declare(strict_types=1);

namespace Plaisio\Form\Test\Control\Traits;

use Plaisio\Form\Control\FieldSet;
use Plaisio\Form\RawForm;

/**
 * Tests for input elements.
 */
trait InputElementTest1
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Overload this method when the class is different form the control type.
   *
   * @return string
   */
  public function getControlClass(): string
  {
    return $this->getControlType();
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test HTML generated by element.
   */
  public function testHtml(): void
  {
    $input = $this->createControl('myInput');

    $fieldSet = new FieldSet('myFieldSet');
    $fieldSet->addFormControl($input);

    $form = new RawForm('myForm');
    $form->addFieldSet($fieldSet);

    $html     = $form->htmlForm();
    $expected = sprintf('<form method="post" action="/" class="frm-form"><fieldset class="frm-fieldset"><input class="frm-%s" type="%s" name="myForm[myFieldSet][myInput]"/></fieldset></form>', $this->getControlClass(), $this->getControlType());
    self::assertSame($expected, $html);
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
