<?php
declare(strict_types=1);

namespace Plaisio\Form\Test\Control\Traits;

use Plaisio\Form\Control\FieldSet;
use Plaisio\Form\RawForm;

/**
 *
 */
trait TestInputElement
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test HTML generated by element.
   */
  public function testHtml(): void
  {
    $input = $this->createControl('myInput');

    $fieldSet = new FieldSet('myFieldSet');
    $fieldSet->addFormControl($input);

    $form = new RawForm('myForm');
    $form->addFieldSet($fieldSet);

    $html     = $form->getHtml();
    $expected = sprintf('<form method="post" action="/"><fieldset class="frm"><input class="frm frm-input" type="%s" name="myForm[myFieldSet][myInput]"/></fieldset></form>', $this->getControlType());
    self::assertSame($expected, $html);
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
