<?php
declare(strict_types=1);

namespace Plaisio\Form\Control;

use Plaisio\Form\Walker\LoadWalker;
use Plaisio\Form\Walker\RenderWalker;
use Plaisio\Helper\Html;
use SetBased\Helper\Cast;

/**
 * A class for pseudo form controls for generating arbitrary HTML code inside forms.
 */
class HtmlControl extends Control
{
  //--------------------------------------------------------------------------------------------------------------------
  /**
   * The HTML code generated by this form control.
   *
   * @var string|null
   */
  protected ?string $value = null;

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @inheritdoc
   *
   * @since 1.0.0
   * @api
   */
  public function getHtml(RenderWalker $walker): string
  {
    $html = $this->prefix;
    $html .= $this->value;
    $html .= $this->postfix;

    return $html;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @inheritdoc
   */
  public function getSetValuesBase(array &$values): void
  {
    $values[$this->name] = $this->value;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns the value of this form control.
   *
   * @return string|null
   *
   * @since 1.0.0
   * @api
   */
  public function getSubmittedValue()
  {
    return $this->value;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @inheritdoc
   */
  public function mergeValuesBase(array $values): void
  {
    if (array_key_exists($this->name, $values))
    {
      $this->setValuesBase($values);
    }
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Sets the (inner) HTML code generated by this form control.
   *
   * @param string|null $htmlSnippet The inner HTML. It is the developer's responsibility to unsure it is valid HTML
   *                                 code.
   *
   * @return $this
   *
   * @since 1.0.0
   * @api
   */
  public function setHtml(?string $htmlSnippet): self
  {
    $this->value = $htmlSnippet;

    return $this;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Sets the (inner) HTML code generated by this form control.
   *
   * @param bool|int|float|string|null $text The text. Special characters will be converted to HTML entities.
   *
   * @return $this
   *
   * @since 1.0.0
   * @api
   */
  public function setText($text): self
  {
    $this->value = Html::txt2Html($text);

    return $this;
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @inheritdoc
   */
  public function setValuesBase(?array $values): void
  {
    $this->value = Cast::toOptString($values[$this->name] ?? null);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * @inheritdoc
   */
  protected function loadSubmittedValuesBase(LoadWalker $walker): void
  {
    $walker->setWithListValue($this->name, $this->value);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Return always true.
   *
   * @param array $invalidFormControls Not used.
   *
   * @return bool
   */
  protected function validateBase(array &$invalidFormControls): bool
  {
    return true;
  }

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
