<?php
declare(strict_types=1);

namespace Plaisio\Form\Test\Control;

use Plaisio\Form\Control\FieldSet;
use Plaisio\Form\Control\ForceSubmitControl;
use Plaisio\Form\Control\PushControl;
use Plaisio\Form\Control\SimpleControl;
use Plaisio\Form\RawForm;
use Plaisio\Form\Test\Control\Traits\CommonSimpleControlTest;
use Plaisio\Form\Test\PlaisioTestCase;

/**
 * Abstract parent class for unit tests for child classes of PushControl.
 */
abstract class PushControlTest extends PlaisioTestCase
{
  //--------------------------------------------------------------------------------------------------------------------
  use CommonSimpleControlTest;

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test HTML generated by element.
   */
  public function testHtml(): void
  {
    $input = $this->createControl('myInput');

    $fieldSet = new FieldSet('myFieldSet');
    $fieldSet->addFormControl($input);

    $form = new RawForm('myForm');
    $form->addFieldSet($fieldSet);

    $html     = $form->htmlForm();
    $expected = sprintf('<input class="frm-%s" type="%s" name="myForm[myFieldSet][myInput]"/>',
                        $this->getControlType(),
                        $this->getControlType());
    self::assertStringContainsString($expected, $html);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test control is hidden.
   */
  public function testIsHidden(): void
  {
    $control = $this->createControl('hidden');

    self::assertSame(false, $control->isHidden());
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Test is submit trigger.
   */
  public function testIsSubmitTrigger(): void
  {
    $input = $this->createControl('trigger');

    self::assertTrue($input->isSubmitTrigger());
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method loadSubmittedValuesBase must set the white list value but not the change controls.
   */
  public function testLoadSubmittedValues1(): void
  {
    $_POST['button'] = 'Do not push';

    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue('Do not push')
          ->setMethod('handleSubmit');
    $fieldset->addFormControl($input);

    $method  = $form->execute();
    $values  = $form->getValues();
    $changed = $form->getChangedControls();

    self::assertTrue($form->isValid());
    self::assertSame('handleSubmit', $method);
    self::assertEquals('Do not push', $values['button']);
    self::assertArrayNotHasKey('button', $changed);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method loadSubmittedValuesBase must only load white listed values.
   */
  public function testLoadSubmittedValues2(): void
  {
    $_POST['button'] = 'Do push me';

    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue('Do not push')
          ->setMethod('handleSubmit');
    $fieldset->addFormControl($input);

    $method  = $form->execute();
    $values  = $form->getValues();
    $changed = $form->getChangedControls();

    self::assertArrayNotHasKey('button', $changed);

    if (get_class($input)!==ForceSubmitControl::class)
    {
      self::assertNull($form->isValid());
      self::assertSame('', $method);
      self::assertArrayNotHasKey('button', $values);
    }
    else
    {
      self::assertTrue($form->isValid());
      self::assertSame('handleSubmit', $method);
      self::assertArrayHasKey('button', $values);
    }
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method loadSubmittedValuesBase must work int values too.
   */
  public function testLoadSubmittedValues3(): void
  {
    $_POST['button'] = '123';

    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue(123)
          ->setMethod('handleSubmit');
    $fieldset->addFormControl($input);

    $method  = $form->execute();
    $values  = $form->getValues();
    $changed = $form->getChangedControls();

    self::assertTrue($form->isValid());
    self::assertSame('handleSubmit', $method);
    self::assertEquals(123, $values['button']);
    self::assertArrayNotHasKey('button', $changed);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method mergeValue() has no effect for buttons.
   */
  public function testMergeValues(): void
  {
    // Create form.
    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue("Do not push");
    $fieldset->addFormControl($input);

    // Set the values for button.
    $values['button'] = 'Do push me';
    $form->mergeValues($values);

    // Generate HTML.
    $html = $form->htmlForm();

    $doc = new \DOMDocument();
    $doc->loadXML($html);
    $xpath = new \DOMXpath($doc);

    // Names of buttons must be absolute setValue has no effect for buttons.
    $list = $xpath->query("/form/fieldset/input[@name='button' and @value='Do not push' and @type='".$this->getControlType()."']");
    self::assertEquals(1, $list->length);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method searchSubmitHandler must return the appropriate handler.
   */
  public function testSearchSubmitHandler1(): void
  {
    $_POST['button'] = 'Do not push';

    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue('Do not push')
          ->setMethod('myMethod');
    $fieldset->addFormControl($input);

    $handler = $form->execute();

    self::assertEquals('myMethod', $handler);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method searchSubmitHandler must return the appropriate handler with int values too.
   */
  public function testSearchSubmitHandler2(): void
  {
    $_POST['123'] = '456';

    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('123');
    $input->setValue(456)
          ->setMethod('myMethod');
    $fieldset->addFormControl($input);

    $handler = $form->execute();

    self::assertEquals('myMethod', $handler);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Method setValue() has no effect for buttons.
   */
  public function testSetValues(): void
  {
    // Create form.
    $form     = new RawForm();
    $fieldset = new FieldSet();
    $form->addFieldSet($fieldset);

    $input = $this->createControl('button');
    $input->setValue("Do not push");
    $fieldset->addFormControl($input);

    // Set the values for button.
    $values['button'] = 'Do push me';
    $form->setValues($values);

    // Generate HTML.
    $html = $form->htmlForm();

    $doc = new \DOMDocument();
    $doc->loadXML($html);
    $xpath = new \DOMXpath($doc);

    // Names of buttons must be absolute setValue has no effect for buttons.
    $list = $xpath->query("/form/fieldset/input[@name='button' and @value='Do not push' and @type='".$this->getControlType()."']");
    self::assertEquals(1, $list->length);
  }

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Returns a concrete instance of PushControl.
   *
   * @param string|null $name The of the control.
   *
   * @return PushControl
   */
  abstract protected function createControl(?string $name): SimpleControl;

  //--------------------------------------------------------------------------------------------------------------------
  /**
   * Return type of form control.
   *
   * @return string
   */
  abstract protected function getControlType(): string;

  //--------------------------------------------------------------------------------------------------------------------
}

//----------------------------------------------------------------------------------------------------------------------
